### ISSUE TITLE
Double reference expected using &'static str as a key

### ISSUE THREAD

**Issue by kmdouglass** [thejpster/multi-map#3]
Hello!

I have found what I think may be a bug in either the definition of a new MultiMap type or the `multimap` macro. Consider the following code:

```rust
use multi_map::{multimap, MultiMap};

type Foo = MultiMap<usize, &'static str, String>;

fn main() {
    let foo: Foo = multimap!{
        1, "bar" => String::from("baz"),
    };

    println!("{}", foo.get_alt("bar").unwrap());
}
```

I would expect that I could use `"bar"` (whose type is `&'static str`) as the alternative key in the example above due to my definition of the `Foo` type. However, the code fails to compile with the following error:

```
error[E0308]: mismatched types
  --> src/main.rs:10:32
   |
10 |     println!("{}", foo.get_alt("bar").unwrap());
   |                                ^^^^^ expected &str, found str
   |
   = note: expected type `&&str`
              found type `&'static str`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: could not compile `multi_map`.
```

Apparently, the argument to `get_alt` is expecting an argument of type `&&str` despite the fact that I have defined the type parameter for the alternative index of the MultiMap as `&'static str`.

Do you think that this is a bug, or am I simply misusing the library?

Thanks a lot!

**Comment by thejpster** [comment]
As with the standard HashMap (https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.get), I believe that for some key type K, get takes &K. In their examples, they store a String and can access with &str. As you are storing &str you need to access with &&str (e.g. &"test").

For types that are Copy, this does seem a little odd, but I believe it's the only way to handle non-copy types with get() consuming your lookup value.

**Comment by kmdouglass** [comment]
Thanks for the explanation @thejpster . I think that you're right in that it is not a bug, but more-or-less my own confusion over using `Copy` types as keys.

I will close the issue.
